import snacks from '../snacks.json';

export type ExpoSnackProps = {
    /**
     * Component name — looks up the Snack ID from apps/docs/snacks.json,
     * which is regenerated by `node apps/docs/scripts/generate-snacks.mjs`.
     * Use this for every v0.1 component; falls through to `id` for one-offs.
     */
    component?: keyof typeof snacks;
    /** Explicit Snack ID escape hatch for Snacks not in snacks.json. */
    id?: string;
    platform?: 'ios' | 'android' | 'web';
    preview?: boolean;
    theme?: 'light' | 'dark';
    height?: number;
};

/**
 * Embeds an Expo Snack for native previews. Snacks are free and hosted by
 * Expo — consumers can fork and run the example on a real device by scanning
 * a QR code. No Expo account is required to view.
 */
export function ExpoSnack({
    component,
    id,
    platform = 'ios',
    preview = true,
    theme = 'light',
    height = 500,
}: ExpoSnackProps) {
    const snackId = component ? snacks[component] : id;
    if (!snackId) {
        return (
            <div role="alert" style={{ padding: 12, border: '1px dashed #e4e4e7', borderRadius: 8, color: '#71717a' }}>
                Snack not available — pass <code>component</code> or <code>id</code>.
            </div>
        );
    }

    const params = new URLSearchParams({
        platform,
        preview: preview ? 'true' : 'false',
        theme,
    });
    const src = `https://snack.expo.dev/embedded/${snackId}?${params.toString()}`;
    return (
        <iframe
            title={`Expo Snack · ${component ?? snackId}`}
            src={src}
            style={{
                width: '100%',
                height,
                border: '1px solid #e4e4e7',
                borderRadius: 8,
            }}
            loading="lazy"
        />
    );
}
