// tokens/src/config.mjs
// Style Dictionary v4 config. Registers two custom formats (tailwind-preset, theme-types)
// and three build targets (light theme, dark theme, TS types).
//
// Invoked by: `yarn workspace @nori-ui/tokens build` (which runs `node src/config.mjs`).

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

import tailwindPresetFormat from './formats/tailwind-preset.mjs';
import themeTypesFormat from './formats/theme-types.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tokensRoot = path.resolve(__dirname, '..'); // tokens/
const buildDir = path.resolve(tokensRoot, 'build');

StyleDictionary.registerFormat(tailwindPresetFormat);
StyleDictionary.registerFormat(themeTypesFormat);

async function buildForMode(mode /* 'light' | 'dark' */) {
    const sd = new StyleDictionary({
        source: [
            path.join(tokensRoot, 'src/tokens/core/*.json'),
            path.join(tokensRoot, `src/tokens/semantic/${mode}.json`),
        ],
        platforms: {
            css: {
                transformGroup: 'css',
                buildPath: `${buildDir}/`,
                files: [
                    {
                        destination: `theme.${mode}.css`,
                        format: 'css/variables',
                        options: {
                            selector: mode === 'light' ? ':root' : '[data-theme="dark"]',
                            outputReferences: false,
                        },
                    },
                ],
            },
            tailwind: {
                transformGroup: 'js',
                buildPath: `${buildDir}/`,
                files: [
                    {
                        destination: `tailwind-preset.${mode}.cjs`,
                        format: 'nori-ui/tailwind-preset',
                        options: { mode },
                    },
                ],
            },
            ts: {
                transformGroup: 'js',
                buildPath: `${buildDir}/`,
                files: [
                    {
                        destination: `theme.${mode}.ts`,
                        format: 'nori-ui/theme-types',
                        options: { mode },
                    },
                ],
            },
        },
        log: {
            warnings: 'warn',
            verbosity: 'default',
            errors: { brokenReferences: 'throw' },
        },
    });

    await sd.cleanAllPlatforms();
    await sd.buildAllPlatforms();
}

async function mergeTailwindPresets() {
    const fs = await import('node:fs/promises');
    const light = await fs.readFile(`${buildDir}/tailwind-preset.light.cjs`, 'utf8');
    const dark = await fs.readFile(`${buildDir}/tailwind-preset.dark.cjs`, 'utf8');

    // Both preset files export an object; combine into one with dark-mode class variants.
    const merged = `// GENERATED by @nori-ui/tokens — DO NOT EDIT.\n// Run \`yarn build:tokens\` to regenerate.\n\n${light.replace('module.exports = ', 'const light = ')}\n${dark.replace('module.exports = ', 'const dark = ')}\n\nmodule.exports = {\n    darkMode: ['class', '[data-theme="dark"]'],\n    theme: {\n        extend: {\n            ...light.theme.extend,\n            colors: { ...light.theme.extend.colors, dark: dark.theme.extend.colors },\n        },\n    },\n};\n`;
    await fs.writeFile(`${buildDir}/tailwind-preset.cjs`, merged, 'utf8');
    await fs.rm(`${buildDir}/tailwind-preset.light.cjs`);
    await fs.rm(`${buildDir}/tailwind-preset.dark.cjs`);
}

async function mergeThemeTypes() {
    const fs = await import('node:fs/promises');
    const light = await fs.readFile(`${buildDir}/theme.light.ts`, 'utf8');
    const dark = await fs.readFile(`${buildDir}/theme.dark.ts`, 'utf8');

    // light.ts has the full interface; dark.ts already exports `themeDark` per the format.
    const merged = `// GENERATED by @nori-ui/tokens — DO NOT EDIT.\n// Run \`yarn build:tokens\` to regenerate.\n\n${light}\n\n// Dark mode overrides\n${dark}\n`;
    await fs.writeFile(`${buildDir}/theme.ts`, merged, 'utf8');
    await fs.rm(`${buildDir}/theme.light.ts`);
    await fs.rm(`${buildDir}/theme.dark.ts`);
}

async function mergeCss() {
    const fs = await import('node:fs/promises');
    const light = await fs.readFile(`${buildDir}/theme.light.css`, 'utf8');
    const dark = await fs.readFile(`${buildDir}/theme.dark.css`, 'utf8');

    const merged = `/* GENERATED by @nori-ui/tokens — DO NOT EDIT. */\n/* Run \`yarn build:tokens\` to regenerate. */\n\n${light}\n${dark}`;
    await fs.writeFile(`${buildDir}/theme.css`, merged, 'utf8');
    await fs.rm(`${buildDir}/theme.light.css`);
    await fs.rm(`${buildDir}/theme.dark.css`);
}

async function main() {
    await buildForMode('light');
    await buildForMode('dark');
    await mergeTailwindPresets();
    await mergeThemeTypes();
    await mergeCss();
    console.log('✓ tokens built');
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
